# ONLY CHANGE THE VALUE AFTER THE ' : '

# Choose the maze in which you want to play.
# 1 : Default Maze
# 2 : Casali Maze

Maze : 1

# Choose the number of ghosts between 1 to 4.

GhostNumber : 4

# Choose the difficulty between 1 to 3

Difficulty : 2

# Choose pacman and ghosts skins.
# 1 : default skin
# 2 : Ice Skin
# 3 : Sugar Skin
# 4 : Garden Skin

Pacman : 1
Ghost : 1

# KeyBinding

KeyUp : z
KeyDown : s
KeyRight : d
KeyLeft : q

# Random Mode (true or false)
# impact Skins, KeyBinding and GhostNumber

RandomSkins : true
RandomKeys : false
