# ONLY CHANGE THE VALUE AFTER THE ' : '

# Choose the maze in which you want to play.
# 1 : Default Maze
# 2 : Casali Maze

Maze : 2

# Choose the number of ghosts betwwen 1 to 4.

GhostNumber : 4

# Choose pacman and ghosts skins.
# 1 : default skin

Pacman : 4
Ghost : 4

# Keybinding

KeyUp : z
KeyDown : s
KeyRight : d
KeyLeft : q
